sudo: true
dist: trusty
language: cpp
before_install:
  - wget http://download.opensuse.org/repositories/home:hpcoder1/xUbuntu_14.04/Release.key
  - sudo apt-key add - < Release.key
  - echo 'deb http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_14.04/ /' >/tmp/hpcoders.list 
  - sudo mv /tmp/hpcoders.list /etc/apt/sources.list.d/
  - sudo apt-get update -qq
  - sudo apt-get install -y tcl-dev
  - sudo apt-get install -y tk-dev
  - sudo apt-get install -y libcairo2-dev
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y libreadline-dev
  - sudo apt-get install -y libgsl0-dev
  - sudo apt-get install -y libpango1.0-dev
  - sudo apt-get install -y exuberant-ctags
  - sudo apt-get install -y libdb-dev
  - sudo apt-get install -y libncurses5-dev
  - sudo apt-get install -y tktable
  - sudo apt-get install -y librsvg2-dev
  - sudo apt-get install -y json-spirit
  - sudo apt-get install -y libboost-dev
  - sudo apt-get install -y libboost-system-dev
  - sudo apt-get install -y libboost-regex-dev
  - sudo apt-get install -y libboost-date-time-dev
  - sudo apt-get install -y libboost-program-options-dev
  - sudo apt-get install -y libboost-filesystem-dev
  - sudo apt-get install -y libboost-thread-dev
  - sudo apt-get install -y libsoci-dev
  - psql -c 'create database minsky;' -U postgres
#addons:
#  postgresql: "9.3"
script: 
  - git clone https://github.com/highperformancecoder/ecolab.git
  - pushd ecolab
  - make install
  - popd
  - make AEGIS=1
  - Xvfb :0 &
  - export DISPLAY=:0
  - echo "testEq.mky" >testDb.dat
  - echo "postgresql://dbname=postgres user=postgres password=">>testDb.dat
  - export MINSKY_TEST_DATABASE_PARAMS=testDb.dat
  - for i in test/00/*; do if sh $i; then true; else exit 1; fi; done
