name: CI Tests

on: [pull_request,push]

jobs:
  Regression-test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ubuntu_ver: [18.04, 20.04]

    name: ubuntu-${{ matrix.ubuntu_ver }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run docker build
        if: matrix.ubuntu_ver == 18.04
        run: |
          docker build --network=host .

